name: Acryl Business Glossary Sync
description: Update your business glossary yaml files with changes from DataHub.
inputs:
  datahub_gms_host:
    description: "DataHub GMS host."
    required: true
  datahub_gms_token:
    description: "DataHub GMS token."
    required: false

  business_glossary_file:
    description: "Path to the business glossary yaml file."
    required: true
  enable_auto_id:
    description: "Set to true if you use `enable_auto_id` in your business glossary ingestion."
    default: "false"
  prune:
    description: "Set to true if you want to use only glossraies from file and not the use from server"
    default: "false"

  debug_mode:
    description: "Set to true to enable debug mode."
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Sync business glossary
      shell: bash
      run: |
        set -x
        pip install -r ${{ github.action_path }}/requirements.txt

        python ${{ github.action_path }}/glossary-sync.py \
          update-glossary-file \
          --enable-auto-id ${{ inputs.enable_auto_id }} \
          --file ${{ inputs.business_glossary_file }} \
          --prune ${{ inputs.prune }}

        git status
      env:
        DATAHUB_GMS_HOST: ${{ inputs.datahub_gms_host }}
        DATAHUB_GMS_TOKEN: ${{ inputs.datahub_gms_token }}
        DEBUG_MODE: ${{ inputs.debug_mode }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: acryl-business-glossary-sync
        commit-message: "[automated] Update business glossary at ${{ inputs.business_glossary_file }}"
        title: Update business glossary
        body: |
          Updates the business glossary at ${{ inputs.business_glossary_file }} with changes from Acryl DataHub.

          Automated changes by [acryldata/business-glossary-sync-action](https://github.com/acryldata/business-glossary-sync-action).

branding:
  icon: "activity"
  color: "green"
